export const tacosArray = [
  {
    'item': 'Asada',
    'itemInEnglish': 'Steak',
    'descriptionInEnglish': 'Seasoned steak on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Biztek Sasonado',
    'price':'$2.50(each)',
    'id': 1,
  },
  {
    'item': 'Pastor',
    'itemInEnglish': 'Pork',
    'descriptionInEnglish': 'Marinated pork in spices on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Puerco marinado en especies',
    'price':'$2.50(each)',
    'id': 2,
  },
  {
    'item': 'Alambre',
    'itemInEnglish': 'Mixed Meats',
    'descriptionInEnglish': 'Steak, ham, chorizo, bell pepper, onion and tomato topped with melted cheese on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Asada y chorizo con queso derretido',
    'price':'$2.50(each)',
    'id': 3,
  },
  {
    'item': 'Cabeza(Res)',
    'itemInEnglish': 'Beef Head',
    'descriptionInEnglish': 'Seasoned beef head on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Cabeza de res sasonado',
    'price':'$2.50(each)',
    'id':4,
  },
  {
    'item': 'Cabeza(Puerco)',
    'itemInEnglish': 'Pork Head',
    'descriptionInEnglish': 'Seasoned pork head on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Cabeza de puerco sasonado',
    'price':'$2.50(each)',
    'id':5,
  },
  {
    'item': 'Carnitas',
    'itemInEnglish': 'Pulled Pork',
    'descriptionInEnglish': 'Seasoned Tender Pork on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Puerco sasonado y tierna',
    'price':'$2.50(each)',
    'id':6,
  },
  {
    'item': 'Carne Molida',
    'itemInEnglish': 'Ground Beef',
    'descriptionInEnglish': 'Seasoned ground beef on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Carne molida y sasonada',
    'price':'$2.50(each)',
    'id':7,
  },
  {
    'item': 'Pollo',
    'itemInEnglish': 'Chicken',
    'descriptionInEnglish': 'Seasoned chicken with fajitas on a corn tortilla with cilantro, onion, and a lime',
    'descriptionInSpanish': 'Pollo sasonado con fajitas',
    'price':'$2.50(each)',
    'id':8,
  }
];
export const tortasArray = [
  {
    'item': 'Asada',
    'itemInEnglish': 'Steak',
    'descriptionInEnglish': 'Seasoned steak in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Biztek Sasonado',
    'price':'$7',
    'id': 1,
  },
  {
    'item': 'Pastor',
    'itemInEnglish': 'Pork',
    'descriptionInEnglish': 'Marinated pork in spices in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Puerco marinado en especies',
    'price':'$7',
    'id': 2,
  },
  {
    'item': 'Alambre',
    'itemInEnglish': 'Mixed Meats',
    'descriptionInEnglish': 'Steak, ham, chorizo, bell pepper, onion and tomato topped with melted cheese in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Asada y chorizo con queso derretido',
    'price':'$7',
    'id': 3,
  },
  {
    'item': 'Cabeza(Res)',
    'itemInEnglish': 'Beef Head',
    'descriptionInEnglish': 'Seasoned beef head in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Cabeza de res sasonado',
    'price':'$7',
    'id':4,
  },
  {
    'item': 'Cabeza(Puerco)',
    'itemInEnglish': 'Pork Head',
    'descriptionInEnglish': 'Seasoned pork head in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Cabeza de puerco sasonado',
    'price':'$7',
    'id':5,
  },
  {
    'item': 'Carnitas',
    'itemInEnglish': 'Pulled Pork',
    'descriptionInEnglish': 'Seasoned Tender Pork in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Puerco sasonado y tierna',
    'price':'$7',
    'id':6,
  },
  {
    'item': 'Carne Molida',
    'itemInEnglish': 'Ground Beef',
    'descriptionInEnglish': 'Seasoned ground beef in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Carne molida y sasonada',
    'price':'$7',
    'id':7,
  },
  {
    'item': 'Pollo',
    'itemInEnglish': 'Chicken',
    'descriptionInEnglish': 'Seasoned chicken with fajitas in white bread with melted cheese, beans, avocado, and tomato',
    'descriptionInSpanish': 'Pollo sasonado con fajitas',
    'price':'$7',
    'id':8,
  }
];

export const quesadillasArray = [
  {
    'item': 'Asada',
    'itemInEnglish': 'Steak',
    'descriptionInEnglish': 'Seasoned steak inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Biztek Sasonado',
    'price':'$5',
    'id': 1,
  },
  {
    'item': 'Pastor',
    'itemInEnglish': 'Pork',
    'descriptionInEnglish': 'Marinated pork in spices inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Puerco marinado en especies',
    'price':'$5',
    'id': 2,
  },
  {
    'item': 'Alambre',
    'itemInEnglish': 'Mixed Meats',
    'descriptionInEnglish': 'Steak, ham, chorizo, bell pepper, onion and tomato topped with melted cheese inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Asada y chorizo con queso derretido',
    'price':'$5',
    'id': 3,
  },
  {
    'item': 'Cabeza(Res)',
    'itemInEnglish': 'Beef Head',
    'descriptionInEnglish': 'Seasoned beef head inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Cabeza de res sasonado',
    'price':'$5',
    'id':4,
  },
  {
    'item': 'Cabeza(Puerco)',
    'itemInEnglish': 'Pork Head',
    'descriptionInEnglish': 'Seasoned pork head inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Cabeza de puerco sasonado',
    'price':'$5',
    'id':5,
  },
  {
    'item': 'Carnitas',
    'itemInEnglish': 'Pulled Pork',
    'descriptionInEnglish': 'Seasoned Tender Pork inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Puerco sasonado y tierna',
    'price':'$5',
    'id':6,
  },
  {
    'item': 'Carne Molida',
    'itemInEnglish': 'Ground Beef',
    'descriptionInEnglish': 'Seasoned ground beef inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Carne molida y sasonada',
    'price':'$5',
    'id':7,
  },
  {
    'item': 'Pollo',
    'itemInEnglish': 'Chicken',
    'descriptionInEnglish': 'Seasoned chicken with fajitas inside of a flour tortilla mixed with melted cheese',
    'descriptionInSpanish': 'Pollo sasonado con fajitas',
    'price':'$5',
    'id':8,
  }
];

export const flautasArray = [
  {
    'item': '3 Flautas De Pollo',
    'itemInEnglish': 'Chicken',
    'descriptionInEnglish': 'Seasoned, shredded chicken in a rolled fried taco topped with lettuce, sour cream and cheese',
    'descriptionInSpanish': 'Pollo sasonado, y deshebrado',
    'price':'$7',
    'id': 1,
  },
  {
    'item': '3 Flautas Desebrada ',
    'itemInEnglish': 'Shredded Beef',
    'descriptionInEnglish': 'Seasoned, shredded beef in a rolled fried taco topped with lettuce, sour cream and cheese',
    'descriptionInSpanish': 'Carne sasonado, y deshebrado',
    'price':'$7',
    'id': 2,
  }
];

export const aguasFrescasArray = [
  {
    'item': 'Agua De Horchata',
    'itemInEnglish': '',
    'descriptionInEnglish': 'Agua de horchata in english',
    'descriptionInSpanish': 'Agua de horchata how cool in spanish',
    'price':'$5',
    'id': 1,
  },
  {
    'item': 'Agua De Jamaica',
    'itemInEnglish': 'Hibiscus Juice',
    'descriptionInEnglish': 'Agua de Jamaica in english',
    'descriptionInSpanish': 'Agua de Jamaica how cool in spanish',
    'price':'$5',
    'id': 2,
  },
  {
    'item': 'Agua De Piña',
    'itemInEnglish': 'Pineapple Juice',
    'descriptionInEnglish': 'Agua de piña in english',
    'descriptionInSpanish': 'Agua de piña how cool in spanish',
    'price':'$5',
    'id': 3,
  },
  {
    'item': 'Agua De Limon',
    'itemInEnglish': 'Lemonade',
    'descriptionInEnglish': 'Agua de piña in english',
    'descriptionInSpanish': 'Agua de piña how cool in spanish',
    'price':'$5',
    'id': 4,
  },  
  {
    'item': 'Agua De Sandia',
    'itemInEnglish': 'Watermelon Juice',
    'descriptionInEnglish': 'Agua de piña in english',
    'descriptionInSpanish': 'Agua de piña how cool in spanish',
    'price':'$5',
    'id': 5,
  },
  {
    'item': 'Agua De Melon',
    'itemInEnglish': 'Cantaloupe Juice',
    'descriptionInEnglish': 'Agua de piña in english',
    'descriptionInSpanish': 'Agua de piña how cool in spanish',
    'price':'$5',
    'id': 6,
  },
  {
    'item': 'Agua De Maracuya',
    'itemInEnglish': 'Passion Fruit Juice',
    'descriptionInEnglish': 'Agua de piña in english',
    'descriptionInSpanish': 'Agua de piña how cool in spanish',
    'price':'$5',
    'id': 7,
  },
  {
    'item': 'Piña Colada',
    'itemInEnglish': 'Pineapple Colada',
    'descriptionInEnglish': 'Agua de piña in english',
    'descriptionInSpanish': 'Agua de piña how cool in spanish',
    'price':'$5',
    'id': 8,
  },
];

export const bottledDrinksArray = [
  {
    'item': 'Agua',
    'itemInEnglish': 'Bottled Water',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$1',
    'id': 1,
  },
  {
    'item': 'Coca Cola',
    'itemInEnglish': 'Coke',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$2',
    'id': 2,
  },
  {
    'item': 'Sprite',
    'itemInEnglish': 'Sprite',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$2',
    'id': 3,
  },
  {
    'item': 'Jarritos',
    'itemInEnglish': 'Jarritos',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 4,
  },
];

export const flansArray = [
  {
    'item': 'Flan',
    'itemInEnglish': 'Flan',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3.50',
    'id': 1,
  },
  {
    'item': 'Chocoflan',
    'itemInEnglish': 'Cocolate Flan',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$4',
    'id': 2,
  },
];


export const gelatinsArray = [
  {
    'item': 'Gelatina',
    'itemInEnglish': 'Gelatin',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3.50',
    'id': 1,
  },
  {
    'item': 'Gelatina con Crema',
    'itemInEnglish': 'Gelatin with Cream',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$4',
    'id': 2,
  },
  {
    'item': 'Gelatina con Fruta',
    'itemInEnglish': 'Gelatin with Fruit',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$4',
    'id': 3,
  },
];

export const empanadasArray = [
  {
    'item': 'Empanada de Piña',
    'itemInEnglish': 'Pineapple Empanada',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 1,
  },
  {
    'item': 'Empanada de Crema Bavara Francesa',
    'itemInEnglish': 'French Bavarian Cream Empanada',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 2,
  },
  {
    'item': 'Empanada de Caramelo',
    'itemInEnglish': 'Toffee Empanada',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 3,
  },
  {
    'item': 'Empanada de Batata',
    'itemInEnglish': 'Sweet Potato Empanada ',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 4,
  },
  {
    'item': 'Empanada de Manzana',
    'itemInEnglish': 'Apple Empanada',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 5,
  },
];

export const cakesArray = [
  {
    'item': 'Pastel de Tres Leches',
    'itemInEnglish': 'Three Milks Cake',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'',
    'id': 1,
  },
  {
    'item': 'Pastel de Chocolate',
    'itemInEnglish': 'Chocolate Cake',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'',
    'id': 2,
  },
  {
    'item': 'Pastel de Vanilla',
    'itemInEnglish': 'Vanilla Cake',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'',
    'id': 3,
  },
  {
    'item': 'Relleno De Fresa',
    'itemInEnglish': 'Strawberry Filling',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'',
    'id': 4,
  },

];

export const cheesecakesArray = [
  {
    'item': 'Fresa',
    'itemInEnglish': 'Strawberry',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'descriptionInSpanish': '',
    'price':'$15',
    'id': 1,
  },
  {
    'item': 'Ceresa',
    'itemInEnglish': 'Cherry',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$15',
    'id': 2,
  },
  {
    'item': 'Mango',
    'itemInEnglish': 'Mango',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$15',
    'id': 3,
  },
  {
    'item': 'Oreo',
    'itemInEnglish': 'Oreo',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$15',
    'id': 4,
  },
  {
    'item': 'Original',
    'itemInEnglish': 'Original',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$15',
    'id': 5,
  },
];

export const piesArray = [
  {
    'item': 'Manzana',
    'itemInEnglish': 'Apple',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$20',
    'id': 1,
  },
  {
    'item': 'Calabaza',
    'itemInEnglish': 'Pumpkin',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$20',
    'id': 2,
  },
  {
    'item': 'Elote',
    'itemInEnglish': 'Corn',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$20',
    'id': 3,
  },
];

export const paletasArray = [
  {
    'item': 'Limon',
    'itemInEnglish': 'Lime',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 1,
  },
  {
    'item': 'Coco',
    'itemInEnglish': 'Coconut',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 2,
  },
  {
    'item': 'Vanilla',
    'itemInEnglish': 'Vanilla',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 3,
  },
  {
    'item': 'Fresa',
    'itemInEnglish': 'Strawberry',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 4,
  },
  {
    'item': 'Rompope',
    'itemInEnglish': 'Eggnog',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 5,
  },
  {
    'item': 'Mango',
    'itemInEnglish': 'Mango',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$3',
    'id': 6,
  },
];

export const cookiesArray = [
  {
    'item': 'Galletas de Vanilla',
    'itemInEnglish': 'Vanilla Cookies',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$1',
    'id': 1,
  },
  {
    'item': 'Galletas de Chocolate',
    'itemInEnglish': 'Chocolate Cookies',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$1',
    'id': 2,
  },
  {
    'item': 'Galletas de Chocolate Chip',
    'itemInEnglish': 'Chocolate Chip Cookies',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'$1.50',
    'id': 3,
  },
  {
    'item': 'Galletas de Temporada',
    'itemInEnglish': 'Seasonal Cookies',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'',
    'id': 4,
  },
  {
    'item': 'Galletas Mexicanas de Matrimonio',
    'itemInEnglish': 'Mexican Wedding Cookies',
    'descriptionInEnglish': '',
    'descriptionInSpanish': '',
    'price':'',
    'id': 5,
  },
];